[project]
name = "walmart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "RISHII", email = "93994298+RISHII7@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "psycopg[binary]>=3.3.4",
    "python-dotenv>=1.2.2",
]

[project.scripts]
walmart = "walmart:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
